#!/bin/bash

function description {
    echo "Delete a server"
}

function print_help {
    echo
    echo 'Usage:  certificate server delete <organization_id> <server_fqdn>'
    echo
    echo $(description)
}

function run {
    case `argc` in
        0)
            print_help
            exit
            ;;
        2)
            ;;
        *)
            invalid_arguments
            ;;
    esac

    local organization_id="`arg 1`"
    local organization_dir="$CERT_LIBDIR/$organization_id"
    if [ ! -d "$organization_dir" ];
    then
        log_err "Organization does not exist!"
        fail
    fi

    local server_fqdn="`arg 2`"
    local server_dir="$organization_dir/servers/$server_fqdn"
    if [ ! -d "$server_dir" ];
    then
        log_err "Server does not exist!"
        fail
    else
        local confirm
        read -p "Delete existing? (y/N) : " confirm
        if [ ! "$confirm" = y ]; then
            log_err "Not deleting. Aborting!"
            fail
        fi
    fi

    rm -r "$server_dir"
}