#!/bin/bash

function description {
    echo "Returns if the server has been defined"
}

function print_help {
    echo
    echo 'Usage:  certificate server exist <organization_id> <server_fqdn>'
    echo
    echo $(description)
}

function run {
    case `argc` in
        0)
            print_help
            exit
            ;;
        2)
            ;;
        *)
            invalid_arguments
            ;;
    esac

    local organization_id="`arg 1`"
    local organization_dir="$CERT_LIBDIR/$organization_id"
    if [ ! -d "$organization_dir" ];
    then
        log_err "Organization does not exist!"
        fail
    fi

    local server_fqdn="`arg 2`"
    local certificate_file="$organization_dir/servers/$server_fqdn/client.crt"
    if [ -f "$certificate_file" ];
    then
        echo "yes"
    else
        echo "no"
    fi
}