#!/bin/bash

function description {
    echo "Adds a new user to an organization"
}

function print_help {
    echo
    echo 'Usage:  certificate user add <organization_id> <username>'
    echo
    echo $(description)
}

function run {
    if [ `argc` -eq 2 ]; then
        invalid_arguments
    fi

    local organization_id="`arg 1`"
    local organization_dir="$CERT_LIBDIR/$organization_id"
    if [ ! -d "$organization_dir" ];
       then
       log_err "Organization does not exist!"
       fail
    fi

    local check=$(invoke_self authority exist "$organization_id")
    if [ "$check" != "yes" ]; then
        log_err "No certificate authority present!"
        fail
    fi

    local username="`arg 2`"
    local user_dir="$organization_dir/users/$username"
    if [ -d "$user_dir" ]; then
        log_err "User already present!"
        fail
    fi

    local ca_srl_file="$organization_dir/CA/ca.srl"
    local ca_key_file="$organization_dir/CA/ca.key"
    local ca_crt_file="$organization_dir/CA/ca.crt"

    ask_passphrase_in "Enter passphrase to read CA key: "
    ask_passphrase_out "Enter passphrase for user private key: "

    local email_address
    read -p "email address: " email_address

    source "$organization_dir/organization.cfg"
    local subject
    subject="/C="$(escape_slash "$CONF_COUNTRY_CODE")"/ST="$(escape_slash "$CONF_STATE_OR_PROVINCE_NAME")"/L="$(escape_slash "$CONF_LOCALITY_NAME")"/O="$(escape_slash "$CONF_ORGANIZATION_NAME")"/CN=$username"
    SAN="email:$email_address"

    umask 077
    mkdir -p "$user_dir"

    openssl req \
        -utf8 \
        -config "$OPENSSL_CONF_PATH" \
        -subj "$subject" \
        -out "$user_dir/client.csr" \
        -newkey rsa:4096 \
        -keyout "$user_dir/client.key" \
        -passout "pass:$PASSPHRASE_OUT"

    openssl x509 \
        -req \
        -extfile "$OPENSSL_CONF_PATH" \
        -extensions v3_client_req \
        -days 365 \
        -in "$user_dir/client.csr" \
        -CAcreateserial \
        -CAserial "$ca_srl_file" \
        -CA "$ca_crt_file" \
        -CAkey "$ca_key_file" \
        -passin "pass:$PASSPHRASE_IN" \
        -out "$user_dir/client.crt"

    openssl pkcs12 \
        -passin "pass:$PASSPHRASE_OUT" \
        -passout "pass:$PASSPHRASE_OUT" \
        -export \
        -clcerts \
        -in "$user_dir"/client.crt \
        -inkey "$user_dir"/client.key \
        -out "$user_dir"/client.p12

    openssl rsa \
        -in "$user_dir"/client.key \
        -des3 \
        -passin "pass:$PASSPHRASE_OUT" \
        -passout "pass:$PASSPHRASE_OUT" \
        -out "$user_dir/client.id_rsa"

    ssh-keygen -y -P "$PASSPHRASE_OUT" -f "$user_dir"/client.id_rsa > "$user_dir"/client.id_rsa.pub

    echo "User added"
}
